#if !canImport(ObjectiveC)
import XCTest

extension ApiKeysControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApiKeysControllerTests = [
        ("testChangeApiKeyName", testChangeApiKeyName),
        ("testCreateApiKey", testCreateApiKey),
        ("testDeleteApiKey", testDeleteApiKey),
        ("testGetApiKeysForTeam", testGetApiKeysForTeam),
        ("testGetApiKeysForUser", testGetApiKeysForUser),
        ("testGetOneApiKey", testGetOneApiKey),
        ("testLinuxTests", testLinuxTests),
    ]
}

extension AppsControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppsControllerTests = [
        ("testAppIconIsRetrieved", testAppIconIsRetrieved),
        ("testAppIconIsRetrievedFromLocalStore", testAppIconIsRetrievedFromLocalStore),
        ("testAppSearch", testAppSearch),
        ("testAppTags", testAppTags),
        ("testAppUploadsToRightTeamAndCluster", testAppUploadsToRightTeamAndCluster),
        ("testAuthReturnsValidToken", testAuthReturnsValidToken),
        ("testBadTokenUpload", testBadTokenUpload),
        ("testCantDeleteOtherPeoplesApp", testCantDeleteOtherPeoplesApp),
        ("testDeleteApp", testDeleteApp),
        ("testDeleteCluster", testDeleteCluster),
        ("testDownloadAndroidApp", testDownloadAndroidApp),
        ("testDownloadIosApp", testDownloadIosApp),
        ("testGetApp", testGetApp),
        ("testGetApps", testGetApps),
        ("testGetAppsOverview", testGetAppsOverview),
        ("testGetAppsOverviewSortedByNameAsc", testGetAppsOverviewSortedByNameAsc),
        ("testGetAppsThroughFilter", testGetAppsThroughFilter),
        ("testIosApp", testIosApp),
        ("testLinuxTests", testLinuxTests),
        ("testObfuscatedApkUploadWithJWTAuth", testObfuscatedApkUploadWithJWTAuth),
        ("testOldIosApp", testOldIosApp),
        ("testOldIosAppTokenUpload", testOldIosAppTokenUpload),
        ("testOldIosAppWithInfo", testOldIosAppWithInfo),
        ("testPartialAppSearch", testPartialAppSearch),
        ("testPartialInsensitiveAppSearch", testPartialInsensitiveAppSearch),
        ("testPlistForApp", testPlistForApp),
        ("testUnobfuscatedApkUploadWithJWTAuth", testUnobfuscatedApkUploadWithJWTAuth),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApiKeysControllerTests.__allTests__ApiKeysControllerTests),
        testCase(AppsControllerTests.__allTests__AppsControllerTests),
    ]
}
#endif
