version: '2.4'

services:
    api:
        image: apphub20/apphost-base:1.0
        volumes:
            - .:/app
        working_dir: /app
        restart: on-failure
        environment:
            APICORE_STORAGE_LOCAL_ROOT: /home/apphost

            APICORE_SERVER_NAME: "Apphost"
            APICORE_SERVER_PATH_PREFIX: ~
            APICORE_SERVER_MAX_UPLOAD_FILESIZE: 800

            APICORE_DATABASE_HOST: postgres
            APICORE_DATABASE_USER: lynn
            APICORE_DATABASE_PASSWORD: try123
            APICORE_DATABASE_DATABASE: apphost
            APICORE_DATABASE_PORT: 5432
            APICORE_DATABASE_LOGGING: 'false'

            APICORE_STORAGE_S3_ENABLED: 'false'

            APICORE_JWT_SECRET: secret

        command: ["swift", "run", "AppHost", "serve", "--hostname", "0.0.0.0", "--port", "8080"]

    postgres:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_USER: lynn
            POSTGRES_PASSWORD: try123
            POSTGRES_DB: apphost
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U lynn -d apphost"]
            interval: 5s
            timeout: 5s
            retries: 5

    adminer:
        image: michalhosna/adminer:master
        environment:
            ADMINER_DB: apphost
            ADMINER_DRIVER: pgsql
            ADMINER_PASSWORD: try123
            ADMINER_SERVER: postgres
            ADMINER_USERNAME: apphost
            ADMINER_AUTOLOGIN: 1
            ADMINER_NAME: Apphost
        depends_on:
            - postgres
